name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_STAGING }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS_PRODUCTION }}
        run: echo ${{ secrets.KNOWN_HOSTS_PRODUCTION }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Upload to remote server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP_NOTIFICATION }}
      run: scp -P 8805 -o StrictHostKeyChecking=no -r ./test.txt ubuntu@$SERVER_IP:/home/ubuntu/
